name: Hackerrank Sync

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Hackerrank
        run: |
          # Клонируем репозиторий Hackerrank
          git clone <URL_ВАШЕГО_РЕПОЗИТОРИЯ_HACKERRANK> hackerrank

          # Копируем файлы из репозитория на GitHub в репозиторий Hackerrank
          cp -R <ПУТЬ_К_ВАШЕМУ_РЕПОЗИТОРИЮ_GITHUB>/. hackerrank

          # Переходим в папку с репозиторием Hackerrank
          cd hackerrank

          # Зафиксируем изменения и отправим их в репозиторий Hackerrank
          git add .
          git commit -m "Sync Hackerrank with GitHub"
          git push origin main  # Замените на вашу основную ветку
