name: Sync HackerRank

on:
  workflow_dispatch:
  schedule:
      - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          resume: ${{ secrets.RESUME }}
          _hjSessionUser_2036154: ${{ secrets._HJSESSIONUSER_2036154 }}
          destination-folder: problems
